/**
 @description
    * This file contains the prompt template for generating a Change Management Plan.
 
 * Optimized for small language models (e.g., Mistral Small)
 */

export const CHANGE_PLAN_PROMPT = `
# Change Management Plan

You are an expert Change Management consultant tasked with creating a concise, actionable Change Management Plan.

PROJECT CONTEXT:
- Name: {projectName}
- Goal: {projectGoal}
- Timeline: {startDate} to {endDate}
- Impacted Users: {impactedUsers}
- Key Stakeholders: {stakeholders}
- Org Benefits: {orgBenefits}
- User Benefits: {userBenefits}
- Challenges: {challenges}

INSTRUCTIONS:
Create a focused Change Management Plan with these sections:

1. Executive Summary (3-4 sentences summarizing the change and approach)

2. Project Timeline (list 4-5 key milestones with dates)

3. Stakeholder Analysis (identify 3-4 stakeholder groups, their interests, and engagement strategies)

4. Change Strategy (outline 3 distinct phases: Preparation, Implementation, Reinforcement)

5. Communication Plan (specify 3-4 key messages, channels, and timing)

6. Training Approach (recommend 2-3 specific training methods)

7. Risk Mitigation (identify 3-4 key risks and specific mitigation actions)

8. Success Metrics (list 3-4 measurable indicators of successful change adoption)

Use clear, direct language. Format in Markdown with ## for section headers and bullet points for lists.

_Generated by VibeOCM AI - https://github.com/adihere/vibeocm_

*Disclaimer: This draft needs to be refined to suit the context further.*
`

