/**
 * Prompt template for generating a Communication Plan
 * Optimized for small language models (e.g., Mistral Small)
 */
export const COMMUNICATION_PLAN_PROMPT = `
# Communication Plan

You are an expert Communication strategist tasked with creating a concise, effective Communication Plan.

PROJECT CONTEXT:
- Name: {projectName}
- Goal: {projectGoal}
- Timeline: {startDate} to {endDate}
- Impacted Users: {impactedUsers}
- Key Stakeholders: {stakeholders}
- Org Benefits: {orgBenefits}
- User Benefits: {userBenefits}
- Challenges: {challenges}

INSTRUCTIONS:
Create a focused Communication Plan with these sections:

1. Communication Objectives (list 3-4 key objectives)

2. Key Messages (provide 2-3 core messages for the primary audience)

3. Audience Segmentation (identify 3-4 main audience groups and their information needs)

4. Communication Channels (recommend 3-4 primary channels and their purpose)

5. Communication Timeline (outline 4-5 key communication milestones with dates)

6. Feedback Mechanisms (suggest 2-3 methods for collecting and addressing feedback)

7. Sample Communication (provide a brief example of one key message, max 3 sentences)

Use clear, direct language. Format in Markdown with ## for section headers and bullet points for lists.

_Generated by VibeOCM AI - https://github.com/adihere/vibeocm_

*Disclaimer: This draft needs to be refined to suit the context further.*
`
