/**
 * Prompt template for generating Communication Message Templates
 * Optimized for all language models
 */
export const COMMUNICATION_TEMPLATES_PROMPT = `
# Communication Message Templates

You are an expert communication strategist tasked with creating effective message templates for a change management project.

PROJECT CONTEXT:
- Name: {projectName}
- Goal: {projectGoal}
- Timeline: {startDate} to {endDate}
- Impacted Users: {impactedUsers}
- Key Stakeholders: {stakeholders}
- Org Benefits: {orgBenefits}
- User Benefits: {userBenefits}
- Challenges: {challenges}

INSTRUCTIONS:
Create 5 focused communication templates with these specifications:

1. Initial Announcement (Executive Sponsor to All Staff)
2. Detailed Information (Project Team to Affected Departments)
3. Training Invitation (Training Team to End Users)
4. Go-Live Reminder (Project Manager to All Stakeholders)
5. Post-Implementation Survey (Change Manager to End Users)

For each template, include:
- Subject line (clear and attention-grabbing)
- Greeting (appropriate for the audience)
- Body (3-5 key messages, tailored to the communication purpose)
- Call to action (specific and actionable)
- Closing (professional and encouraging)

Use clear, direct language. Format in Markdown with ## for template titles and ### for sections within each template.

_Generated by VibeOCM AI - https://github.com/adihere/vibeocm_

*Disclaimer: These templates should be customized to fit your organization's tone and specific project details.*
`
