/**
 * Prompt template for generating Feedback Survey Templates
 * Optimized for small language models (e.g., Mistral Small)
 */
export const FEEDBACK_SURVEY_PROMPT = `
# Feedback Survey Templates

You are an expert survey designer tasked with creating concise, effective feedback surveys.

PROJECT CONTEXT:
- Name: {projectName}
- Goal: {projectGoal}
- Timeline: {startDate} to {endDate}
- Impacted Users: {impactedUsers}
- Key Stakeholders: {stakeholders}
- Org Benefits: {orgBenefits}
- User Benefits: {userBenefits}
- Challenges: {challenges}

INSTRUCTIONS:
Create 4 focused survey templates with these specifications:

1. Pre-implementation Readiness Assessment
   - Brief introduction (2-3 sentences)
   - 5 questions (2 multiple choice, 2 rating scale, 1 open-ended)
   - Short thank you message (1 sentence)

2. Training Effectiveness Survey
   - Brief introduction (2-3 sentences)
   - 5 questions (2 multiple choice, 2 rating scale, 1 open-ended)
   - Short thank you message (1 sentence)

3. Post-implementation Satisfaction Survey
   - Brief introduction (2-3 sentences)
   - 5 questions (2 multiple choice, 2 rating scale, 1 open-ended)
   - Short thank you message (1 sentence)

4. 30-Day Follow-up Survey
   - Brief introduction (2-3 sentences)
   - 5 questions (2 multiple choice, 2 rating scale, 1 open-ended)
   - Short thank you message (1 sentence)

Use clear, direct language. Format in Markdown with ## for survey titles, ### for sections, and numbered lists for questions.

_Generated by VibeOCM AI - https://github.com/adihere/vibeocm_

*Disclaimer: This draft needs to be refined to suit the context further.*
`
// Note: This template is designed to be concise and effective for small language models.